[beam]
species = "70Zn"  # Use "AEl" notation, e.g. 17F where A=17 El(ement) = F
energy_fwhm = 7.0 # Beam energy FWHM [MeV]
dedx_scale = 1.0  # Beam stopping power scale factor

[target]
species = "1H"
compound = "71Ga"

[detector]
eloss_bins = 300 # Number of bins for y axis
max_eloss = 50.0 # Max y value [MeV]
strip = -1       # Strip where reaction takes place. Use -1 for unreacted beam
eres = 0.05      # Energy noise level (sigma) in each strip [MeV]

[[reaction.step]]
evap = { name = "1H", color = 2 }                    # Integer. See ROOT colors.
res = { name = "70Zn", color = 4, dedx_scale = 1.0 } # Integer. See ROOT colors.

[run]
n_events = 1000                # Number of events simulated
wait = 0                       # Wait between simulated events? 1=yes, 0=no
update = 0                     # Update graphics between simulated events? 1=yes, 0=no
max_time = 2000.0              # Maximum time for an event [ns]
sim_step = 0.001               # Simulation step size [cm]
method = 0
output = "unreacted_70Zn.root"
file_opt = "recreate"
print_opt = 0
