[gas]
species = "4He"     # Fill gas: 4He, 3He, Ar, CF4, CH4, P10, iC4H10
pressure = 220.0    # Torr
temperature = 293.0 # K

[beam]
species = "37Cl"  # Use "AEl" notation
energy = 92.0     # Beam KE at the accelerator (before entrance window) [MeV]
energy_fwhm = 0.9 # Beam energy FWHM at accelerator [MeV]
dedx_scale = 1.0  # Beam stopping power scale factor

[target]
species = "4He"
compound = "41K"

[windows.entrance]
# mg/cm^2 areal density
material = "Ti"
thickness_mg_cm2 = 0.9

[windows.exit]
# mg/cm^2 areal density
material = "Ti"
thickness_mg_cm2 = 1.3

[windows.degrader]
# Bulk degrader upstream of entrance window (empty = none) / microns along beam axis
material = "Mylar"
thickness_um = 6.0

[detector]
eloss_bins = 555 # Number of bins for y axis
max_eloss = 10.0 # Max y value [MeV]
strip = 6        # Strip where reaction takes place. Use -1 for unreacted beam
eres = 0.05      # Energy noise level (sigma) in each strip [MeV]

[[reaction.step]]
[reaction.step.evap]
name = "n"
color = 4

[reaction.step.res]
name = "40K"
color = 3
dedx_scale = 1.0

[run]
n_events = 20
threads = 1
wait = 1                                   # Pause between events; double-click canvas to advance
update = 1                                 # Render EVE 3D view + trace canvas
max_time = 2000.0                          # ns
sim_step = 0.001                           # cm
method = 0
output = "traces_37Cl_an_interactive.root"
file_opt = "recreate"
print_opt = 0
