[gas]
species     = "4He"
pressure    = 500.0 # Torr; recovered from the legacy stopping-table configuration
temperature = 293.0 # K

[beam]
species = "98Zr" # Use "AEl" notation, e.g. 17F where A=17 El(ement) = F
energy  = 400.0  # Gas-entry KE in the legacy control [MeV]

[target]
species  = "4He"
compound = "102Mo"

[windows.entrance]
thickness_mg_cm2 = -1

[windows.exit]
thickness_mg_cm2 = -1

[detector]
eloss_bins      = 300  # Number of bins for y axis
max_eloss       = 25.0 # Max y value [MeV]
strip           = 12   # Strip where reaction takes place. Use -1 for unreacted beam
noise_sigma_mev = 0.05 # Energy noise level in each strip [MeV]

[[reaction.step]]
residue_excitation   = "forced"
angular_distribution = "isotropic"
[reaction.step.evap]
# Integer see ROOT colors
name  = "n"
color = 632

[reaction.step.res]
name = "101Mo"

[[reaction.step]]
residue_excitation   = "ground"
angular_distribution = "isotropic"
[reaction.step.evap]
# Integer see ROOT colors
name  = "n"
color = 432

[reaction.step.res]
name = "100Mo"

[run]
seed             = 12345
events_per_strip = 300                     # Number of events simulated
wait             = 0                       # Wait between simulated events? 1=yes, 0=no
update           = 0                       # Update graphics between simulated events? 1=yes, 0=no
max_time         = 2000.0                  # Maximum time for an event [ns]
sim_step         = 0.001                   # Simulation step size [cm]
method           = 0
output           = "traces_a2n_stp12.root"
file_opt         = "recreate"
print_opt        = 0
